"use client";

import type { JuryCandidate, JuryVerdict } from "@/lib/types";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

function ratingVariant(rating: JuryCandidate["rating"]) {
  if (rating === "BUY_NOW") return "success" as const;
  if (rating === "STAGED_ENTRY") return "info" as const;
  if (rating === "SELL" || rating === "AVOID") return "destructive" as const;
  return "warning" as const;
}

function CandidateCard({ candidate }: { candidate: JuryCandidate }) {
  return <Card><CardHeader className="pb-3"><div className="flex flex-wrap items-center gap-2"><CardTitle className="text-base">{candidate.rank ? `#${candidate.rank} ` : ""}{candidate.ticker}</CardTitle><Badge variant={ratingVariant(candidate.rating)}>{candidate.rating}</Badge><Badge variant="muted">{candidate.portfolio_status}</Badge><span className="ml-auto text-sm text-muted-foreground">{Math.round(candidate.conviction * 100)}% conviction</span></div></CardHeader><CardContent className="space-y-4 text-sm"><p className="text-foreground">{candidate.summary}</p><div className="grid gap-3 md:grid-cols-2"><div><h4 className="font-medium text-foreground">Why this rating</h4><ul className="mt-1 list-disc space-y-1 pl-4 text-muted-foreground">{candidate.supporting_evidence.map((item, i) => <li key={`support-${i}`}>{item}</li>)}</ul></div><div><h4 className="font-medium text-foreground">Counterevidence</h4><ul className="mt-1 list-disc space-y-1 pl-4 text-muted-foreground">{candidate.counter_evidence.map((item, i) => <li key={`counter-${i}`}>{item}</li>)}</ul></div><div><h4 className="font-medium text-foreground">Why it wins or loses</h4><p className="mt-1 text-muted-foreground">{candidate.comparative_advantages.concat(candidate.comparative_disadvantages).join(" ") || "No comparative explanation supplied."}</p></div><div><h4 className="font-medium text-foreground">Why it may underperform</h4><p className="mt-1 text-muted-foreground">{candidate.underperformance_scenario || "No underperformance scenario supplied."}</p></div></div><div className="grid gap-3 border-t border-border pt-3 md:grid-cols-3"><div><h4 className="font-medium text-foreground">Catalysts</h4><p className="text-muted-foreground">{candidate.catalysts.join(" ") || "None identified."}</p></div><div><h4 className="font-medium text-foreground">Risks</h4><p className="text-muted-foreground">{candidate.key_risks.join(" ") || "None identified."}</p></div><div><h4 className="font-medium text-foreground">Compared with</h4><p className="text-muted-foreground">Better than: {candidate.better_than.join(", ") || "—"}<br />Lost to: {candidate.lost_to.join(", ") || "—"}</p></div></div>{candidate.allocation_pct > 0 && <p className="font-medium text-foreground">Allocation: {candidate.allocation_pct}%</p>}{candidate.data_quality_warnings.length > 0 && <p className="rounded bg-amber-500/10 p-2 text-xs text-amber-700 dark:text-amber-300">Data warnings: {candidate.data_quality_warnings.join(" ")}</p>}</CardContent></Card>;
}

export function StockJuryReport({ verdict }: { verdict: JuryVerdict }) {
  const isProgress = !verdict.schema_version && verdict.candidate_runs;
  if (isProgress) return <Card><CardHeader><CardTitle className="text-base">Analyzing selected stocks</CardTitle></CardHeader><CardContent className="space-y-2">{verdict.candidate_runs?.map((candidate) => <div key={candidate.ticker} className="flex justify-between rounded bg-muted/50 px-3 py-2 text-sm"><span>{candidate.ticker}</span><Badge variant={candidate.status === "completed" ? "success" : candidate.status === "failed" ? "destructive" : "warning"}>{candidate.status}</Badge></div>)}</CardContent></Card>;
  return <div className="space-y-5"><Card><CardContent className="space-y-3 p-5"><div className="flex flex-wrap items-center gap-3"><h2 className="text-xl font-bold text-foreground">Jury verdict</h2><Badge variant={verdict.decision === "ACTIONABLE" ? "success" : "warning"}>{verdict.decision}</Badge>{verdict.prompt_version && <Badge variant="muted">{verdict.prompt_version}</Badge>}</div><p className="text-sm text-foreground">{verdict.market_view}</p><p className="text-sm text-muted-foreground">{verdict.portfolio_reasoning}</p><p className="text-sm font-medium text-foreground">Cash allocation: {verdict.cash_allocation_pct}%</p></CardContent></Card><div className="space-y-3">{verdict.candidates.map((candidate) => <CandidateCard key={candidate.ticker} candidate={candidate} />)}</div>{(verdict.concentration_risks.length > 0 || verdict.data_quality_warnings.length > 0) && <Card><CardHeader><CardTitle className="text-base">Warnings</CardTitle></CardHeader><CardContent className="space-y-1 text-sm text-muted-foreground">{verdict.concentration_risks.concat(verdict.data_quality_warnings).map((warning, i) => <p key={i}>• {warning}</p>)}</CardContent></Card>}</div>;
}
